services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    env_file:
      - ./db/.env
    volumes:
      - db_data:/var/lib/mysql
      - ./db/nm-gmt.sql:/docker-entrypoint-initdb.d/nm-gmt.sql
    ports:
      - "3306:3306"
    networks:
      - docker-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      retries: 5
  
  backend:
    build:
      context: /home/devops/Downloads/medicaar_backend/
      dockerfile: Dockerfile
    image: nm-backend:v1
    container_name: backend
    restart: always
    ports:
      - "7000:7000"
    env_file:
      - /home/ubuntu/gmt-nm/.env_be
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - docker-network
  
  frontend:
    build: 
      context: /home/devops/Downloads/medicaar
      dockerfile: Dockerfile
    image: nm-frontend:v1
    container_name: frontend
    restart: always
    ports: 
      - "8080:80"
    env_file:
      - /home/devops/Downloads/medicaar/.env
    depends_on:
      - backend
    networks:
      - docker-network
volumes:
  db_data:

networks:
  docker-network:
    driver: bridge
